// <auto-generated />
using System;
using System.Collections.Generic;
using AccesoDatos.RepositoriosEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250522174644_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.BarraProgreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("tablaEquivalenciaId")
                        .HasColumnType("int");

                    b.Property<int>("valorMax")
                        .HasColumnType("int");

                    b.Property<int>("valorMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("tablaEquivalenciaId");

                    b.ToTable("BarrasProgreso");
                });

            modelBuilder.Entity("Dominio.EnlaceUnion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("codigoBase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("expiracion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EnlacesUnion");
                });

            modelBuilder.Entity("Dominio.Equivalencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("TablaEquivalenciaId")
                        .HasColumnType("int");

                    b.Property<int>("nota")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TablaEquivalenciaId");

                    b.ToTable("Equivalencias");
                });

            modelBuilder.Entity("Dominio.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EnlaceUnionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<int>("TablaEquivalenciaId")
                        .HasColumnType("int");

                    b.Property<int>("TiendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnlaceUnionId")
                        .IsUnique()
                        .HasFilter("[EnlaceUnionId] IS NOT NULL");

                    b.HasIndex("Nombre");

                    b.HasIndex("ProfesorId")
                        .HasDatabaseName("IX_Grupo_ProfesorId");

                    b.HasIndex("TablaEquivalenciaId");

                    b.HasIndex("TiendaId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Dominio.Hito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("cantMedallasRequeridas")
                        .HasColumnType("int");

                    b.Property<int>("recompensaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("recompensaId");

                    b.ToTable("Hitos");
                });

            modelBuilder.Entity("Dominio.Medalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquivalenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PerfilEstudianteId")
                        .HasColumnType("int");

                    b.Property<int?>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<int?>("RendimientoPeriodoId")
                        .HasColumnType("int");

                    b.Property<bool>("asignacionMutua")
                        .HasColumnType("bit");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("monedasOtorgadas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquivalenciaId");

                    b.HasIndex("Nombre");

                    b.HasIndex("PerfilEstudianteId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("RendimientoPeriodoId");

                    b.ToTable("Medallas");
                });

            modelBuilder.Entity("Dominio.PerfilEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int?>("TablaClasificacionId")
                        .HasColumnType("int");

                    b.Property<int>("avatarGrupoId")
                        .HasColumnType("int");

                    b.Property<int>("barraProgresoId")
                        .HasColumnType("int");

                    b.Property<string>("enlaceAvatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("metaCalificacion")
                        .HasColumnType("int");

                    b.Property<int>("monedas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("TablaClasificacionId");

                    b.HasIndex("barraProgresoId");

                    b.HasIndex("GrupoId", "EstudianteId")
                        .IsUnique()
                        .HasDatabaseName("UX_PerfilEstudiante_GrupoId_EstudianteId");

                    b.ToTable("PerfilesEstudiantes");
                });

            modelBuilder.Entity("Dominio.Pin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("fCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("fueUtilizado")
                        .HasColumnType("bit");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<string>("pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tiempoDeVida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pines");
                });

            modelBuilder.Entity("Dominio.PreguntaRespuestaSeguridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("pregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("respuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("PreguntasRespuestasSeguridad");
                });

            modelBuilder.Entity("Dominio.Recompensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PerfilEstudianteId")
                        .HasColumnType("int");

                    b.Property<int?>("TiendaId")
                        .HasColumnType("int");

                    b.Property<string>("imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("PerfilEstudianteId");

                    b.HasIndex("TiendaId");

                    b.ToTable("Recompensas");

                    b.HasDiscriminator().HasValue("Recompensa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dominio.RendimientoPeriodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("notaObtenida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("perfilEstudianteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("perfilEstudianteId");

                    b.ToTable("RendimientosPeriodos");
                });

            modelBuilder.Entity("Dominio.SolicitudUnion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("GrupoId");

                    b.ToTable("SolicitudesUnion");
                });

            modelBuilder.Entity("Dominio.TablaClasificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("grupoId")
                        .HasColumnType("int");

                    b.Property<int>("medallaAsociadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("grupoId");

                    b.HasIndex("medallaAsociadaId");

                    b.ToTable("TablasClasificacion");
                });

            modelBuilder.Entity("Dominio.TablaEquivalencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("ProfesorId");

                    b.ToTable("TablasEquivalencia");
                });

            modelBuilder.Entity("Dominio.Tienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tiendas");
                });

            modelBuilder.Entity("Dominio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.ComplexProperty<Dictionary<string, object>>("NombreCompleto", "Dominio.Usuario.NombreCompleto#NombreCompleto", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator().HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dominio.Potenciador", b =>
                {
                    b.HasBaseType("Dominio.Recompensa");

                    b.Property<double>("multiplicador")
                        .HasColumnType("float");

                    b.Property<DateTime>("periodo")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Potenciador");
                });

            modelBuilder.Entity("Dominio.Estudiante", b =>
                {
                    b.HasBaseType("Dominio.Usuario");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("Dominio.Profesor", b =>
                {
                    b.HasBaseType("Dominio.Usuario");

                    b.HasDiscriminator().HasValue("Profesor");
                });

            modelBuilder.Entity("Dominio.BarraProgreso", b =>
                {
                    b.HasOne("Dominio.TablaEquivalencia", "tablaEquivalencia")
                        .WithMany()
                        .HasForeignKey("tablaEquivalenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tablaEquivalencia");
                });

            modelBuilder.Entity("Dominio.Equivalencia", b =>
                {
                    b.HasOne("Dominio.TablaEquivalencia", null)
                        .WithMany("equivalencias")
                        .HasForeignKey("TablaEquivalenciaId");
                });

            modelBuilder.Entity("Dominio.Grupo", b =>
                {
                    b.HasOne("Dominio.EnlaceUnion", "EnlaceUnion")
                        .WithOne()
                        .HasForeignKey("Dominio.Grupo", "EnlaceUnionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dominio.Profesor", null)
                        .WithMany("grupos")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.TablaEquivalencia", "TablaEquivalencia")
                        .WithMany()
                        .HasForeignKey("TablaEquivalenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Tienda", "Tienda")
                        .WithMany()
                        .HasForeignKey("TiendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnlaceUnion");

                    b.Navigation("TablaEquivalencia");

                    b.Navigation("Tienda");
                });

            modelBuilder.Entity("Dominio.Hito", b =>
                {
                    b.HasOne("Dominio.Estudiante", null)
                        .WithMany("hitos")
                        .HasForeignKey("EstudianteId");

                    b.HasOne("Dominio.Recompensa", "recompensa")
                        .WithMany()
                        .HasForeignKey("recompensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("recompensa");
                });

            modelBuilder.Entity("Dominio.Medalla", b =>
                {
                    b.HasOne("Dominio.Equivalencia", null)
                        .WithMany("medallasNecesarias")
                        .HasForeignKey("EquivalenciaId");

                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithMany("medallasObtenidas")
                        .HasForeignKey("PerfilEstudianteId");

                    b.HasOne("Dominio.Profesor", null)
                        .WithMany("medallas")
                        .HasForeignKey("ProfesorId");

                    b.HasOne("Dominio.RendimientoPeriodo", null)
                        .WithMany("medallasObtuvoEstudiante")
                        .HasForeignKey("RendimientoPeriodoId");
                });

            modelBuilder.Entity("Dominio.PerfilEstudiante", b =>
                {
                    b.HasOne("Dominio.Estudiante", "Estudiante")
                        .WithMany("perfiles")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Grupo", "Grupo")
                        .WithMany("Alumnos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.TablaClasificacion", null)
                        .WithMany("participantes")
                        .HasForeignKey("TablaClasificacionId");

                    b.HasOne("Dominio.BarraProgreso", "barraProgreso")
                        .WithMany()
                        .HasForeignKey("barraProgresoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Grupo");

                    b.Navigation("barraProgreso");
                });

            modelBuilder.Entity("Dominio.PreguntaRespuestaSeguridad", b =>
                {
                    b.HasOne("Dominio.Estudiante", null)
                        .WithMany("preguntasSeguridad")
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("Dominio.Recompensa", b =>
                {
                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithMany("inventario")
                        .HasForeignKey("PerfilEstudianteId");

                    b.HasOne("Dominio.Tienda", null)
                        .WithMany("Recompesas")
                        .HasForeignKey("TiendaId");
                });

            modelBuilder.Entity("Dominio.RendimientoPeriodo", b =>
                {
                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithMany("historialRendimientoPeriodos")
                        .HasForeignKey("perfilEstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LogicaNegocio.ValueObject.RangoFechas", "rangofecha", b1 =>
                        {
                            b1.Property<int>("RendimientoPeriodoId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("fechaFin")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("fechaInicio")
                                .HasColumnType("datetime2");

                            b1.HasKey("RendimientoPeriodoId");

                            b1.ToTable("RendimientosPeriodos");

                            b1.WithOwner()
                                .HasForeignKey("RendimientoPeriodoId");
                        });

                    b.Navigation("rangofecha")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.SolicitudUnion", b =>
                {
                    b.HasOne("Dominio.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Grupo", "Grupo")
                        .WithMany("Solicitudes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Dominio.TablaClasificacion", b =>
                {
                    b.HasOne("Dominio.Grupo", null)
                        .WithMany("TablasClasificacion")
                        .HasForeignKey("grupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Medalla", "medallaAsociada")
                        .WithMany()
                        .HasForeignKey("medallaAsociadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("medallaAsociada");
                });

            modelBuilder.Entity("Dominio.TablaEquivalencia", b =>
                {
                    b.HasOne("Dominio.Profesor", null)
                        .WithMany("tablasEquivalencia")
                        .HasForeignKey("ProfesorId");
                });

            modelBuilder.Entity("Dominio.Usuario", b =>
                {
                    b.OwnsOne("LogicaNegocio.ValueObjects.Contrasenia", "Contrasenia", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Clave")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("LogicaNegocio.ValueObjects.NombreUsuario", "NombreUsuario", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Nombre")
                                .IsUnique();

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Contrasenia")
                        .IsRequired();

                    b.Navigation("NombreUsuario")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Profesor", b =>
                {
                    b.OwnsOne("LogicaNegocio.ValueObjects.Email", "correo", b1 =>
                        {
                            b1.Property<int>("ProfesorId")
                                .HasColumnType("int");

                            b1.Property<string>("Correo")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)");

                            b1.HasKey("ProfesorId");

                            b1.HasIndex("Correo")
                                .IsUnique()
                                .HasFilter("[correo_Correo] IS NOT NULL");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("ProfesorId");
                        });

                    b.Navigation("correo")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Equivalencia", b =>
                {
                    b.Navigation("medallasNecesarias");
                });

            modelBuilder.Entity("Dominio.Grupo", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Solicitudes");

                    b.Navigation("TablasClasificacion");
                });

            modelBuilder.Entity("Dominio.PerfilEstudiante", b =>
                {
                    b.Navigation("historialRendimientoPeriodos");

                    b.Navigation("inventario");

                    b.Navigation("medallasObtenidas");
                });

            modelBuilder.Entity("Dominio.RendimientoPeriodo", b =>
                {
                    b.Navigation("medallasObtuvoEstudiante");
                });

            modelBuilder.Entity("Dominio.TablaClasificacion", b =>
                {
                    b.Navigation("participantes");
                });

            modelBuilder.Entity("Dominio.TablaEquivalencia", b =>
                {
                    b.Navigation("equivalencias");
                });

            modelBuilder.Entity("Dominio.Tienda", b =>
                {
                    b.Navigation("Recompesas");
                });

            modelBuilder.Entity("Dominio.Estudiante", b =>
                {
                    b.Navigation("hitos");

                    b.Navigation("perfiles");

                    b.Navigation("preguntasSeguridad");
                });

            modelBuilder.Entity("Dominio.Profesor", b =>
                {
                    b.Navigation("grupos");

                    b.Navigation("medallas");

                    b.Navigation("tablasEquivalencia");
                });
#pragma warning restore 612, 618
        }
    }
}
