// <auto-generated />
using System;
using AccesoDatos.RepositoriosEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(ContextoDb))]
    [Migration("20250619203133_inicialConDatos")]
    partial class inicialConDatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.BarraProgreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PerfilEstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("TablaEquivalenciaId")
                        .HasColumnType("int");

                    b.Property<int>("ValorMax")
                        .HasColumnType("int");

                    b.Property<int>("ValorMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilEstudianteId")
                        .IsUnique();

                    b.HasIndex("TablaEquivalenciaId");

                    b.ToTable("BarrasProgreso");
                });

            modelBuilder.Entity("Dominio.EnlaceUnion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlCompleta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EnlacesUnion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoUnico = "MAT1A25",
                            Expiracion = new DateTime(2026, 4, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            UrlCompleta = "https://www.ludik.app/unirse/MAT1A25"
                        },
                        new
                        {
                            Id = 2,
                            CodigoUnico = "HISTU25",
                            Expiracion = new DateTime(2026, 4, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            UrlCompleta = "https://www.ludik.app/unirse/HISTU25"
                        });
                });

            modelBuilder.Entity("Dominio.Equivalencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<int>("TablaEquivalenciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TablaEquivalenciaId");

                    b.ToTable("Equivalencias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nota = 1,
                            TablaEquivalenciaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nota = 2,
                            TablaEquivalenciaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Nota = 1,
                            TablaEquivalenciaId = 2
                        });
                });

            modelBuilder.Entity("Dominio.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnlaceUnionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProfesorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TablaEquivalenciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnlaceUnionId");

                    b.HasIndex("Nombre");

                    b.HasIndex("ProfesorId")
                        .HasDatabaseName("IX_Grupo_ProfesorId");

                    b.HasIndex("TablaEquivalenciaId");

                    b.ToTable("Grupos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnlaceUnionId = 1,
                            FCreacion = new DateTime(2025, 6, 19, 10, 30, 0, 0, DateTimeKind.Utc),
                            Institucion = "Liceo N°5",
                            Materia = "Matemática",
                            Nombre = "Matemática 1A - 2025",
                            ProfesorId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            TablaEquivalenciaId = 1
                        },
                        new
                        {
                            Id = 2,
                            EnlaceUnionId = 2,
                            FCreacion = new DateTime(2025, 6, 19, 10, 30, 0, 0, DateTimeKind.Utc),
                            Institucion = "Liceo N°5",
                            Materia = "Historia",
                            Nombre = "Historia Universal - 2025",
                            ProfesorId = "9e445865-a24d-4543-a6c6-9443d048cdb0",
                            TablaEquivalenciaId = 2
                        });
                });

            modelBuilder.Entity("Dominio.Hito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantMedallasRequeridas")
                        .HasColumnType("int");

                    b.Property<int>("RecompensaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecompensaId");

                    b.ToTable("Hitos");
                });

            modelBuilder.Entity("Dominio.Medalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonedasOtorgadas")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProfesorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TieneAsignacionMutua")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Medallas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Asistencia y participación en todas las clases del mes.",
                            Icono = "icono_asistencia.png",
                            MonedasOtorgadas = 30,
                            Nombre = "Participación Perfecta",
                            ProfesorId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            TieneAsignacionMutua = false
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Ayuda destacada a compañeros en proyectos grupales.",
                            Icono = "icono_colaboracion.png",
                            MonedasOtorgadas = 25,
                            Nombre = "Maestro de la Colaboración",
                            ProfesorId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            TieneAsignacionMutua = false
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Realización de preguntas perspicaces que enriquecen la clase.",
                            Icono = "icono_pregunta.png",
                            MonedasOtorgadas = 15,
                            Nombre = "Mente Curiosa",
                            ProfesorId = "9e445865-a24d-4543-a6c6-9443d048cdb0",
                            TieneAsignacionMutua = false
                        });
                });

            modelBuilder.Entity("Dominio.PerfilEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstudianteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("MetaCalificacion")
                        .HasColumnType("int");

                    b.Property<int>("Monedas")
                        .HasColumnType("int");

                    b.Property<string>("RutaImagenCompleta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaImagenMiniatura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("GrupoId", "EstudianteId")
                        .IsUnique()
                        .HasDatabaseName("UX_PerfilEstudiante_GrupoId_EstudianteId");

                    b.ToTable("PerfilesEstudiantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstudianteId = "a1445865-a24d-4543-a6c6-9443d048cdb1",
                            GrupoId = 1,
                            MetaCalificacion = 8,
                            Monedas = 120,
                            RutaImagenCompleta = "default/avatar_full.jpg",
                            RutaImagenMiniatura = "default/avatar_thumb.jpg"
                        },
                        new
                        {
                            Id = 2,
                            EstudianteId = "b2445865-a24d-4543-a6c6-9443d048cdb2",
                            GrupoId = 1,
                            MetaCalificacion = 9,
                            Monedas = 150,
                            RutaImagenCompleta = "default/avatar_full.jpg",
                            RutaImagenMiniatura = "default/avatar_thumb.jpg"
                        },
                        new
                        {
                            Id = 3,
                            EstudianteId = "c3445865-a24d-4543-a6c6-9443d048cdb3",
                            GrupoId = 1,
                            MetaCalificacion = 7,
                            Monedas = 95,
                            RutaImagenCompleta = "default/avatar_full.jpg",
                            RutaImagenMiniatura = "default/avatar_thumb.jpg"
                        },
                        new
                        {
                            Id = 4,
                            EstudianteId = "d4445865-a24d-4543-a6c6-9443d048cdb4",
                            GrupoId = 2,
                            MetaCalificacion = 10,
                            Monedas = 200,
                            RutaImagenCompleta = "default/avatar_full.jpg",
                            RutaImagenMiniatura = "default/avatar_thumb.jpg"
                        },
                        new
                        {
                            Id = 5,
                            EstudianteId = "e5445865-a24d-4543-a6c6-9443d048cdb5",
                            GrupoId = 2,
                            MetaCalificacion = 8,
                            Monedas = 180,
                            RutaImagenCompleta = "default/avatar_full.jpg",
                            RutaImagenMiniatura = "default/avatar_thumb.jpg"
                        });
                });

            modelBuilder.Entity("Dominio.Pin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueUtilizado")
                        .HasColumnType("bit");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("TiempoDeVida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pines");
                });

            modelBuilder.Entity("Dominio.PreguntaRespuestaSeguridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("PreguntasRespuestasSeguridad");
                });

            modelBuilder.Entity("Dominio.Recompensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<int?>("TiendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("TiendaId");

                    b.ToTable("Recompensas");

                    b.HasDiscriminator().HasValue("Recompensa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dominio.RendimientoPeriodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NotaObtenida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerfilEstudianteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilEstudianteId");

                    b.ToTable("RendimientosPeriodos");
                });

            modelBuilder.Entity("Dominio.SolicitudUnion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("EstudianteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("GrupoId");

                    b.ToTable("SolicitudesUnion");
                });

            modelBuilder.Entity("Dominio.TablaClasificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("MedallaAsociadaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("MedallaAsociadaId");

                    b.HasIndex("Nombre");

                    b.ToTable("TablasClasificacion");
                });

            modelBuilder.Entity("Dominio.TablaEquivalencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfesorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("ProfesorId");

                    b.ToTable("TablasEquivalencia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Calificaciones Estándar (C. Rodríguez)",
                            ProfesorId = "8e445865-a24d-4543-a6c6-9443d048cdb9"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Evaluación Continua (L. Fernández)",
                            ProfesorId = "9e445865-a24d-4543-a6c6-9443d048cdb0"
                        });
                });

            modelBuilder.Entity("Dominio.Tienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId")
                        .IsUnique();

                    b.ToTable("Tiendas");
                });

            modelBuilder.Entity("Dominio.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("IntentosFallidos");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EstampaConcurrencia");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Correo");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("CorreoConfirmado");

                    b.Property<string>("ImagenPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("BloqueoHabilitado");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FinBloqueo");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CorreoNormalizado");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreUsuarioNormalizado");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContraseniaHash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Telefono");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("TelefonoConfirmado");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EstampaSeguridad");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("AutenticacionDosFactores");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreUsuario");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NombreUsuarioNormalizado] IS NOT NULL");

                    b.ToTable("Usuarios", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EquivalenciaMedallas", b =>
                {
                    b.Property<int>("EquivalenciaId")
                        .HasColumnType("int");

                    b.Property<int>("MedallaId")
                        .HasColumnType("int");

                    b.HasKey("EquivalenciaId", "MedallaId");

                    b.HasIndex("MedallaId");

                    b.ToTable("EquivalenciaMedallas");

                    b.HasData(
                        new
                        {
                            EquivalenciaId = 1,
                            MedallaId = 1
                        },
                        new
                        {
                            EquivalenciaId = 2,
                            MedallaId = 1
                        },
                        new
                        {
                            EquivalenciaId = 2,
                            MedallaId = 2
                        },
                        new
                        {
                            EquivalenciaId = 3,
                            MedallaId = 3
                        });
                });

            modelBuilder.Entity("EstudianteHitos", b =>
                {
                    b.Property<string>("EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HitoId")
                        .HasColumnType("int");

                    b.HasKey("EstudianteId", "HitoId");

                    b.HasIndex("HitoId");

                    b.ToTable("EstudianteHitos");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Avatar", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Barba")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Boca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cejas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorBarba")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorFondo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorGafas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorPelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorPiel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorRopa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColorSombrero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gafas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gorro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoRopa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ojos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProbabilidadBarba")
                        .HasColumnType("int");

                    b.Property<int>("ProbabilidadGafas")
                        .HasColumnType("int");

                    b.Property<string>("Ropa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rotacion")
                        .HasColumnType("int");

                    b.Property<bool>("Voltear")
                        .HasColumnType("bit");

                    b.Property<int>("Zoom")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Avatares");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RolId");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EstampaConcurrencia");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreRol");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreRolNormalizado");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NombreRolNormalizado] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            Name = "Profesor",
                            NormalizedName = "PROFESOR"
                        },
                        new
                        {
                            Id = "3d5e174e-3b0e-446f-86af-483d56fd7211",
                            Name = "Estudiante",
                            NormalizedName = "ESTUDIANTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReclamacionRolId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoReclamacion");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorReclamacion");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RolId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ReclamacionesRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReclamacionUsuarioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoReclamacion");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorReclamacion");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ReclamacionesUsuario", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Proveedor");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ClaveProveedor");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreProveedor");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("IniciosSesionUsuario", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RolId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuariosRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7210"
                        },
                        new
                        {
                            UserId = "9e445865-a24d-4543-a6c6-9443d048cdb0",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7210"
                        },
                        new
                        {
                            UserId = "a1445865-a24d-4543-a6c6-9443d048cdb1",
                            RoleId = "3d5e174e-3b0e-446f-86af-483d56fd7211"
                        },
                        new
                        {
                            UserId = "b2445865-a24d-4543-a6c6-9443d048cdb2",
                            RoleId = "3d5e174e-3b0e-446f-86af-483d56fd7211"
                        },
                        new
                        {
                            UserId = "c3445865-a24d-4543-a6c6-9443d048cdb3",
                            RoleId = "3d5e174e-3b0e-446f-86af-483d56fd7211"
                        },
                        new
                        {
                            UserId = "d4445865-a24d-4543-a6c6-9443d048cdb4",
                            RoleId = "3d5e174e-3b0e-446f-86af-483d56fd7211"
                        },
                        new
                        {
                            UserId = "e5445865-a24d-4543-a6c6-9443d048cdb5",
                            RoleId = "3d5e174e-3b0e-446f-86af-483d56fd7211"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Proveedor");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("NombreToken");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorToken");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("TokensUsuario", (string)null);
                });

            modelBuilder.Entity("PerfilEstudianteMedallas", b =>
                {
                    b.Property<int>("MedallaId")
                        .HasColumnType("int");

                    b.Property<int>("PerfilEstudianteId")
                        .HasColumnType("int");

                    b.HasKey("MedallaId", "PerfilEstudianteId");

                    b.HasIndex("PerfilEstudianteId");

                    b.ToTable("PerfilEstudianteMedallas");
                });

            modelBuilder.Entity("PerfilEstudianteRecompensas", b =>
                {
                    b.Property<int>("PerfilEstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("RecompensaId")
                        .HasColumnType("int");

                    b.HasKey("PerfilEstudianteId", "RecompensaId");

                    b.HasIndex("RecompensaId");

                    b.ToTable("PerfilEstudianteRecompensas");
                });

            modelBuilder.Entity("RendimientoPeriodoMedallas", b =>
                {
                    b.Property<int>("MedallaId")
                        .HasColumnType("int");

                    b.Property<int>("RendimientoPeriodoId")
                        .HasColumnType("int");

                    b.HasKey("MedallaId", "RendimientoPeriodoId");

                    b.HasIndex("RendimientoPeriodoId");

                    b.ToTable("RendimientoPeriodoMedallas");
                });

            modelBuilder.Entity("TablaClasificacionParticipantes", b =>
                {
                    b.Property<int>("PerfilEstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("TablaClasificacionId")
                        .HasColumnType("int");

                    b.HasKey("PerfilEstudianteId", "TablaClasificacionId");

                    b.HasIndex("TablaClasificacionId");

                    b.ToTable("TablaClasificacionParticipantes");
                });

            modelBuilder.Entity("Dominio.Potenciador", b =>
                {
                    b.HasBaseType("Dominio.Recompensa");

                    b.Property<double>("Multiplicador")
                        .HasColumnType("float");

                    b.Property<DateTime>("Periodo")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Potenciador");
                });

            modelBuilder.Entity("Dominio.Estudiante", b =>
                {
                    b.HasBaseType("Dominio.Usuario");

                    b.ToTable("Estudiantes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1445865-a24d-4543-a6c6-9443d048cdb1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c4b6e8a0-1d3f-4e9a-9c8e-5d2a4f6b8c0d",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "SANTIAGO",
                            PasswordHash = "AQAAAAIAAYagAAAAEICeFSdiFCtz68TPDuBQMzkt7RT8ecvoXx3nTwJev5fDDu098ITlRrx8fymingA8Mg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC_SECURITY_STAMP_3",
                            TwoFactorEnabled = false,
                            UserName = "santiago"
                        },
                        new
                        {
                            Id = "b2445865-a24d-4543-a6c6-9443d048cdb2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d5c7f9b1-2e4g-5f0b-a0d9-6e3b5g7c9d1e",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "VALENTINA",
                            PasswordHash = "AQAAAAIAAYagAAAAENuS3fE5d1k/aN2zV8mY9wR8cI7qU5kY4tL6wP9eO3bF0dG1sS5nC2vX3jJ4oP7eWw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC_SECURITY_STAMP_4",
                            TwoFactorEnabled = false,
                            UserName = "valentina"
                        },
                        new
                        {
                            Id = "c3445865-a24d-4543-a6c6-9443d048cdb3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e6d80ac2-3f5h-6g1c-b1e0-7f4c6h8d0e2f",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "MATIAS",
                            PasswordHash = "AQAAAAIAAYagAAAAENuS3fE5d1k/aN2zV8mY9wR8cI7qU5kY4tL6wP9eO3bF0dG1sS5nC2vX3jJ4oP7eWw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC_SECURITY_STAMP_5",
                            TwoFactorEnabled = false,
                            UserName = "matias"
                        },
                        new
                        {
                            Id = "d4445865-a24d-4543-a6c6-9443d048cdb4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f7e91bd3-4g6i-7h2d-c2f1-8g5d7i9e1f3g",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "CAMILA",
                            PasswordHash = "AQAAAAIAAYagAAAAENuS3fE5d1k/aN2zV8mY9wR8cI7qU5kY4tL6wP9eO3bF0dG1sS5nC2vX3jJ4oP7eWw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC_SECURITY_STAMP_6",
                            TwoFactorEnabled = false,
                            UserName = "camila"
                        },
                        new
                        {
                            Id = "e5445865-a24d-4543-a6c6-9443d048cdb5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "g8f02ce4-5h7j-8i3e-d3g2-9h6e8j0f2g4h",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "LUCAS",
                            PasswordHash = "AQAAAAIAAYagAAAAENuS3fE5d1k/aN2zV8mY9wR8cI7qU5kY4tL6wP9eO3bF0dG1sS5nC2vX3jJ4oP7eWw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC_SECURITY_STAMP_7",
                            TwoFactorEnabled = false,
                            UserName = "lucas"
                        });
                });

            modelBuilder.Entity("Dominio.Profesor", b =>
                {
                    b.HasBaseType("Dominio.Usuario");

                    b.ToTable("Profesores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b0c8b6a8-8e6b-4e6a-9e1e-2e0b166a9c76",
                            Email = "cecilia@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "CECILIA@GMAIL.COM",
                            NormalizedUserName = "CECILIA",
                            PasswordHash = "AQAAAAIAAYagAAAAEICeFSdiFCtz68TPDuBQMzkt7RT8ecvoXx3nTwJev5fDDu098ITlRrx8fymingA8Mg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC_SECURITY_STAMP_1",
                            TwoFactorEnabled = false,
                            UserName = "cecilia"
                        },
                        new
                        {
                            Id = "9e445865-a24d-4543-a6c6-9443d048cdb0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a1d3b5e7-9f2d-4b8c-8a1e-3f0e2d5b4a6b",
                            Email = "laura.fernandez@ludik.edu.uy",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LAURA.FERNANDEZ@LUDIK.EDU.UY",
                            NormalizedUserName = "LAURA.FERNANDEZ",
                            PasswordHash = "AQAAAAIAAYagAAAAEICeFSdiFCtz68TPDuBQMzkt7RT8ecvoXx3nTwJev5fDDu098ITlRrx8fymingA8Mg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC_SECURITY_STAMP_2",
                            TwoFactorEnabled = false,
                            UserName = "laura"
                        });
                });

            modelBuilder.Entity("Dominio.BarraProgreso", b =>
                {
                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithOne("BarraProgreso")
                        .HasForeignKey("Dominio.BarraProgreso", "PerfilEstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.TablaEquivalencia", "TablaEquivalencia")
                        .WithMany()
                        .HasForeignKey("TablaEquivalenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TablaEquivalencia");
                });

            modelBuilder.Entity("Dominio.Equivalencia", b =>
                {
                    b.HasOne("Dominio.TablaEquivalencia", "TablaEquivalencia")
                        .WithMany("Equivalencias")
                        .HasForeignKey("TablaEquivalenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TablaEquivalencia");
                });

            modelBuilder.Entity("Dominio.Grupo", b =>
                {
                    b.HasOne("Dominio.EnlaceUnion", "EnlaceUnion")
                        .WithMany()
                        .HasForeignKey("EnlaceUnionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Profesor", "Profesor")
                        .WithMany("Grupos")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.TablaEquivalencia", "TablaEquivalencia")
                        .WithMany()
                        .HasForeignKey("TablaEquivalenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnlaceUnion");

                    b.Navigation("Profesor");

                    b.Navigation("TablaEquivalencia");
                });

            modelBuilder.Entity("Dominio.Hito", b =>
                {
                    b.HasOne("Dominio.Recompensa", "Recompensa")
                        .WithMany()
                        .HasForeignKey("RecompensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recompensa");
                });

            modelBuilder.Entity("Dominio.Medalla", b =>
                {
                    b.HasOne("Dominio.Profesor", "Creador")
                        .WithMany("Medallas")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("Dominio.PerfilEstudiante", b =>
                {
                    b.HasOne("Dominio.Estudiante", null)
                        .WithMany("Perfiles")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Grupo", null)
                        .WithMany("Alumnos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.PreguntaRespuestaSeguridad", b =>
                {
                    b.HasOne("Dominio.Estudiante", null)
                        .WithMany("PreguntasSeguridad")
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("Dominio.Recompensa", b =>
                {
                    b.HasOne("Dominio.Tienda", null)
                        .WithMany("Recompesas")
                        .HasForeignKey("TiendaId");
                });

            modelBuilder.Entity("Dominio.RendimientoPeriodo", b =>
                {
                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithMany("HistorialRendimientoPeriodos")
                        .HasForeignKey("PerfilEstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LogicaNegocio.ValueObject.RangoFechas", "Rangofecha", b1 =>
                        {
                            b1.Property<int>("RendimientoPeriodoId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("fechaFin")
                                .HasColumnType("datetime2")
                                .HasColumnName("FechaFin");

                            b1.Property<DateTime>("fechaInicio")
                                .HasColumnType("datetime2")
                                .HasColumnName("FechaInicio");

                            b1.HasKey("RendimientoPeriodoId");

                            b1.ToTable("RendimientosPeriodos");

                            b1.WithOwner()
                                .HasForeignKey("RendimientoPeriodoId");
                        });

                    b.Navigation("Rangofecha")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.SolicitudUnion", b =>
                {
                    b.HasOne("Dominio.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Grupo", "Grupo")
                        .WithMany("Solicitudes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Dominio.TablaClasificacion", b =>
                {
                    b.HasOne("Dominio.Grupo", null)
                        .WithMany("TablasClasificacion")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Medalla", "MedallaAsociada")
                        .WithMany()
                        .HasForeignKey("MedallaAsociadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedallaAsociada");
                });

            modelBuilder.Entity("Dominio.TablaEquivalencia", b =>
                {
                    b.HasOne("Dominio.Profesor", null)
                        .WithMany("TablasEquivalencia")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Tienda", b =>
                {
                    b.HasOne("Dominio.Grupo", null)
                        .WithOne("Tienda")
                        .HasForeignKey("Dominio.Tienda", "GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Usuario", b =>
                {
                    b.OwnsOne("LogicaNegocio.ValueObjects.NombreCompleto", "NombreCompleto", b1 =>
                        {
                            b1.Property<string>("UsuarioId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Apellido");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Nombre");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");

                            b1.HasData(
                                new
                                {
                                    UsuarioId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                                    Apellido = "Rodríguez",
                                    Nombre = "Carlos"
                                },
                                new
                                {
                                    UsuarioId = "9e445865-a24d-4543-a6c6-9443d048cdb0",
                                    Apellido = "Fernández",
                                    Nombre = "Laura"
                                },
                                new
                                {
                                    UsuarioId = "a1445865-a24d-4543-a6c6-9443d048cdb1",
                                    Apellido = "Pérez",
                                    Nombre = "Santiago"
                                },
                                new
                                {
                                    UsuarioId = "b2445865-a24d-4543-a6c6-9443d048cdb2",
                                    Apellido = "Gómez",
                                    Nombre = "Valentina"
                                },
                                new
                                {
                                    UsuarioId = "c3445865-a24d-4543-a6c6-9443d048cdb3",
                                    Apellido = "González",
                                    Nombre = "Matías"
                                },
                                new
                                {
                                    UsuarioId = "d4445865-a24d-4543-a6c6-9443d048cdb4",
                                    Apellido = "Martínez",
                                    Nombre = "Camila"
                                },
                                new
                                {
                                    UsuarioId = "e5445865-a24d-4543-a6c6-9443d048cdb5",
                                    Apellido = "Silva",
                                    Nombre = "Lucas"
                                });
                        });

                    b.Navigation("NombreCompleto")
                        .IsRequired();
                });

            modelBuilder.Entity("EquivalenciaMedallas", b =>
                {
                    b.HasOne("Dominio.Equivalencia", null)
                        .WithMany()
                        .HasForeignKey("EquivalenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Medalla", null)
                        .WithMany()
                        .HasForeignKey("MedallaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EstudianteHitos", b =>
                {
                    b.HasOne("Dominio.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Hito", null)
                        .WithMany()
                        .HasForeignKey("HitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Avatar", b =>
                {
                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithOne("Avatar")
                        .HasForeignKey("LogicaNegocio.Entidades.Avatar", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PerfilEstudianteMedallas", b =>
                {
                    b.HasOne("Dominio.Medalla", null)
                        .WithMany()
                        .HasForeignKey("MedallaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithMany()
                        .HasForeignKey("PerfilEstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PerfilEstudianteRecompensas", b =>
                {
                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithMany()
                        .HasForeignKey("PerfilEstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Recompensa", null)
                        .WithMany()
                        .HasForeignKey("RecompensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RendimientoPeriodoMedallas", b =>
                {
                    b.HasOne("Dominio.Medalla", null)
                        .WithMany()
                        .HasForeignKey("MedallaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.RendimientoPeriodo", null)
                        .WithMany()
                        .HasForeignKey("RendimientoPeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TablaClasificacionParticipantes", b =>
                {
                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithMany()
                        .HasForeignKey("PerfilEstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.TablaClasificacion", null)
                        .WithMany()
                        .HasForeignKey("TablaClasificacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Estudiante", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Dominio.Estudiante", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Profesor", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Dominio.Profesor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Grupo", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Solicitudes");

                    b.Navigation("TablasClasificacion");

                    b.Navigation("Tienda")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.PerfilEstudiante", b =>
                {
                    b.Navigation("Avatar")
                        .IsRequired();

                    b.Navigation("BarraProgreso")
                        .IsRequired();

                    b.Navigation("HistorialRendimientoPeriodos");
                });

            modelBuilder.Entity("Dominio.TablaEquivalencia", b =>
                {
                    b.Navigation("Equivalencias");
                });

            modelBuilder.Entity("Dominio.Tienda", b =>
                {
                    b.Navigation("Recompesas");
                });

            modelBuilder.Entity("Dominio.Estudiante", b =>
                {
                    b.Navigation("Perfiles");

                    b.Navigation("PreguntasSeguridad");
                });

            modelBuilder.Entity("Dominio.Profesor", b =>
                {
                    b.Navigation("Grupos");

                    b.Navigation("Medallas");

                    b.Navigation("TablasEquivalencia");
                });
#pragma warning restore 612, 618
        }
    }
}
