// <auto-generated />
using System;
using AccesoDatos.RepositoriosEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(ContextoDb))]
    [Migration("20250613180329_actualizacionMedalla")]
    partial class actualizacionMedalla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.BarraProgreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PerfilEstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("TablaEquivalenciaId")
                        .HasColumnType("int");

                    b.Property<int>("ValorMax")
                        .HasColumnType("int");

                    b.Property<int>("ValorMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilEstudianteId")
                        .IsUnique();

                    b.HasIndex("TablaEquivalenciaId");

                    b.ToTable("BarrasProgreso");
                });

            modelBuilder.Entity("Dominio.EnlaceUnion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoUnico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlCompleta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EnlacesUnion");
                });

            modelBuilder.Entity("Dominio.Equivalencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.Property<int?>("TablaEquivalenciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TablaEquivalenciaId");

                    b.ToTable("Equivalencias");
                });

            modelBuilder.Entity("Dominio.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EnlaceUnionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProfesorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TablaEquivalenciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnlaceUnionId");

                    b.HasIndex("Nombre");

                    b.HasIndex("ProfesorId")
                        .HasDatabaseName("IX_Grupo_ProfesorId");

                    b.HasIndex("TablaEquivalenciaId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Dominio.Hito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantMedallasRequeridas")
                        .HasColumnType("int");

                    b.Property<int>("RecompensaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecompensaId");

                    b.ToTable("Hitos");
                });

            modelBuilder.Entity("Dominio.Medalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonedasOtorgadas")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProfesorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TieneAsignacionMutua")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Medallas");
                });

            modelBuilder.Entity("Dominio.PerfilEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvatarGrupoId")
                        .HasColumnType("int");

                    b.Property<string>("EnlaceAvatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstudianteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("MetaCalificacion")
                        .HasColumnType("int");

                    b.Property<int>("Monedas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("GrupoId", "EstudianteId")
                        .IsUnique()
                        .HasDatabaseName("UX_PerfilEstudiante_GrupoId_EstudianteId");

                    b.ToTable("PerfilesEstudiantes");
                });

            modelBuilder.Entity("Dominio.Pin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueUtilizado")
                        .HasColumnType("bit");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("TiempoDeVida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pines");
                });

            modelBuilder.Entity("Dominio.PreguntaRespuestaSeguridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("PreguntasRespuestasSeguridad");
                });

            modelBuilder.Entity("Dominio.Recompensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Precio")
                        .HasColumnType("int");

                    b.Property<int?>("TiendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("TiendaId");

                    b.ToTable("Recompensas");

                    b.HasDiscriminator().HasValue("Recompensa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dominio.RendimientoPeriodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NotaObtenida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerfilEstudianteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilEstudianteId");

                    b.ToTable("RendimientosPeriodos");
                });

            modelBuilder.Entity("Dominio.SolicitudUnion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("EstudianteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("GrupoId");

                    b.ToTable("SolicitudesUnion");
                });

            modelBuilder.Entity("Dominio.TablaClasificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("MedallaAsociadaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("MedallaAsociadaId");

                    b.HasIndex("Nombre");

                    b.ToTable("TablasClasificacion");
                });

            modelBuilder.Entity("Dominio.TablaEquivalencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfesorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("ProfesorId");

                    b.ToTable("TablasEquivalencia");
                });

            modelBuilder.Entity("Dominio.Tienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId")
                        .IsUnique();

                    b.ToTable("Tiendas");
                });

            modelBuilder.Entity("Dominio.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("IntentosFallidos");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EstampaConcurrencia");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Correo");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("CorreoConfirmado");

                    b.Property<string>("ImagenPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("BloqueoHabilitado");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FinBloqueo");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CorreoNormalizado");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreUsuarioNormalizado");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContraseniaHash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Telefono");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("TelefonoConfirmado");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EstampaSeguridad");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("AutenticacionDosFactores");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreUsuario");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NombreUsuarioNormalizado] IS NOT NULL");

                    b.ToTable("Usuarios", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EquivalenciaMedallas", b =>
                {
                    b.Property<int>("EquivalenciaId")
                        .HasColumnType("int");

                    b.Property<int>("MedallaId")
                        .HasColumnType("int");

                    b.HasKey("EquivalenciaId", "MedallaId");

                    b.HasIndex("MedallaId");

                    b.ToTable("EquivalenciaMedallas");
                });

            modelBuilder.Entity("EstudianteHitos", b =>
                {
                    b.Property<string>("EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HitoId")
                        .HasColumnType("int");

                    b.HasKey("EstudianteId", "HitoId");

                    b.HasIndex("HitoId");

                    b.ToTable("EstudianteHitos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RolId");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EstampaConcurrencia");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreRol");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreRolNormalizado");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NombreRolNormalizado] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReclamacionRolId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoReclamacion");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorReclamacion");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RolId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ReclamacionesRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReclamacionUsuarioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoReclamacion");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorReclamacion");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ReclamacionesUsuario", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Proveedor");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ClaveProveedor");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreProveedor");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("IniciosSesionUsuario", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RolId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuariosRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Proveedor");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("NombreToken");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorToken");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("TokensUsuario", (string)null);
                });

            modelBuilder.Entity("PerfilEstudianteMedallas", b =>
                {
                    b.Property<int>("MedallaId")
                        .HasColumnType("int");

                    b.Property<int>("PerfilEstudianteId")
                        .HasColumnType("int");

                    b.HasKey("MedallaId", "PerfilEstudianteId");

                    b.HasIndex("PerfilEstudianteId");

                    b.ToTable("PerfilEstudianteMedallas");
                });

            modelBuilder.Entity("PerfilEstudianteRecompensas", b =>
                {
                    b.Property<int>("PerfilEstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("RecompensaId")
                        .HasColumnType("int");

                    b.HasKey("PerfilEstudianteId", "RecompensaId");

                    b.HasIndex("RecompensaId");

                    b.ToTable("PerfilEstudianteRecompensas");
                });

            modelBuilder.Entity("RendimientoPeriodoMedallas", b =>
                {
                    b.Property<int>("MedallaId")
                        .HasColumnType("int");

                    b.Property<int>("RendimientoPeriodoId")
                        .HasColumnType("int");

                    b.HasKey("MedallaId", "RendimientoPeriodoId");

                    b.HasIndex("RendimientoPeriodoId");

                    b.ToTable("RendimientoPeriodoMedallas");
                });

            modelBuilder.Entity("TablaClasificacionParticipantes", b =>
                {
                    b.Property<int>("PerfilEstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("TablaClasificacionId")
                        .HasColumnType("int");

                    b.HasKey("PerfilEstudianteId", "TablaClasificacionId");

                    b.HasIndex("TablaClasificacionId");

                    b.ToTable("TablaClasificacionParticipantes");
                });

            modelBuilder.Entity("Dominio.Potenciador", b =>
                {
                    b.HasBaseType("Dominio.Recompensa");

                    b.Property<double>("Multiplicador")
                        .HasColumnType("float");

                    b.Property<DateTime>("Periodo")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Potenciador");
                });

            modelBuilder.Entity("Dominio.Estudiante", b =>
                {
                    b.HasBaseType("Dominio.Usuario");

                    b.ToTable("Estudiantes", (string)null);
                });

            modelBuilder.Entity("Dominio.Profesor", b =>
                {
                    b.HasBaseType("Dominio.Usuario");

                    b.ToTable("Profesores", (string)null);
                });

            modelBuilder.Entity("Dominio.BarraProgreso", b =>
                {
                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithOne("BarraProgreso")
                        .HasForeignKey("Dominio.BarraProgreso", "PerfilEstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.TablaEquivalencia", "TablaEquivalencia")
                        .WithMany()
                        .HasForeignKey("TablaEquivalenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TablaEquivalencia");
                });

            modelBuilder.Entity("Dominio.Equivalencia", b =>
                {
                    b.HasOne("Dominio.TablaEquivalencia", null)
                        .WithMany("Equivalencias")
                        .HasForeignKey("TablaEquivalenciaId");
                });

            modelBuilder.Entity("Dominio.Grupo", b =>
                {
                    b.HasOne("Dominio.EnlaceUnion", "EnlaceUnion")
                        .WithMany()
                        .HasForeignKey("EnlaceUnionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Profesor", null)
                        .WithMany("Grupos")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.TablaEquivalencia", "TablaEquivalencia")
                        .WithMany()
                        .HasForeignKey("TablaEquivalenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EnlaceUnion");

                    b.Navigation("TablaEquivalencia");
                });

            modelBuilder.Entity("Dominio.Hito", b =>
                {
                    b.HasOne("Dominio.Recompensa", "Recompensa")
                        .WithMany()
                        .HasForeignKey("RecompensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recompensa");
                });

            modelBuilder.Entity("Dominio.Medalla", b =>
                {
                    b.HasOne("Dominio.Profesor", "Creador")
                        .WithMany("Medallas")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("Dominio.PerfilEstudiante", b =>
                {
                    b.HasOne("Dominio.Estudiante", null)
                        .WithMany("Perfiles")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Grupo", null)
                        .WithMany("Alumnos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.PreguntaRespuestaSeguridad", b =>
                {
                    b.HasOne("Dominio.Estudiante", null)
                        .WithMany("PreguntasSeguridad")
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("Dominio.Recompensa", b =>
                {
                    b.HasOne("Dominio.Tienda", null)
                        .WithMany("Recompesas")
                        .HasForeignKey("TiendaId");
                });

            modelBuilder.Entity("Dominio.RendimientoPeriodo", b =>
                {
                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithMany("HistorialRendimientoPeriodos")
                        .HasForeignKey("PerfilEstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LogicaNegocio.ValueObject.RangoFechas", "Rangofecha", b1 =>
                        {
                            b1.Property<int>("RendimientoPeriodoId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("fechaFin")
                                .HasColumnType("datetime2")
                                .HasColumnName("FechaFin");

                            b1.Property<DateTime>("fechaInicio")
                                .HasColumnType("datetime2")
                                .HasColumnName("FechaInicio");

                            b1.HasKey("RendimientoPeriodoId");

                            b1.ToTable("RendimientosPeriodos");

                            b1.WithOwner()
                                .HasForeignKey("RendimientoPeriodoId");
                        });

                    b.Navigation("Rangofecha")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.SolicitudUnion", b =>
                {
                    b.HasOne("Dominio.Estudiante", "Estudiante")
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Grupo", "Grupo")
                        .WithMany("Solicitudes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Dominio.TablaClasificacion", b =>
                {
                    b.HasOne("Dominio.Grupo", null)
                        .WithMany("TablasClasificacion")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Medalla", "MedallaAsociada")
                        .WithMany()
                        .HasForeignKey("MedallaAsociadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedallaAsociada");
                });

            modelBuilder.Entity("Dominio.TablaEquivalencia", b =>
                {
                    b.HasOne("Dominio.Profesor", null)
                        .WithMany("TablasEquivalencia")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Tienda", b =>
                {
                    b.HasOne("Dominio.Grupo", null)
                        .WithOne("Tienda")
                        .HasForeignKey("Dominio.Tienda", "GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Usuario", b =>
                {
                    b.OwnsOne("LogicaNegocio.ValueObjects.NombreCompleto", "NombreCompleto", b1 =>
                        {
                            b1.Property<string>("UsuarioId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Apellido");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Nombre");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("NombreCompleto")
                        .IsRequired();
                });

            modelBuilder.Entity("EquivalenciaMedallas", b =>
                {
                    b.HasOne("Dominio.Equivalencia", null)
                        .WithMany()
                        .HasForeignKey("EquivalenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Medalla", null)
                        .WithMany()
                        .HasForeignKey("MedallaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EstudianteHitos", b =>
                {
                    b.HasOne("Dominio.Estudiante", null)
                        .WithMany()
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Hito", null)
                        .WithMany()
                        .HasForeignKey("HitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PerfilEstudianteMedallas", b =>
                {
                    b.HasOne("Dominio.Medalla", null)
                        .WithMany()
                        .HasForeignKey("MedallaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithMany()
                        .HasForeignKey("PerfilEstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PerfilEstudianteRecompensas", b =>
                {
                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithMany()
                        .HasForeignKey("PerfilEstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Recompensa", null)
                        .WithMany()
                        .HasForeignKey("RecompensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RendimientoPeriodoMedallas", b =>
                {
                    b.HasOne("Dominio.Medalla", null)
                        .WithMany()
                        .HasForeignKey("MedallaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.RendimientoPeriodo", null)
                        .WithMany()
                        .HasForeignKey("RendimientoPeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TablaClasificacionParticipantes", b =>
                {
                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithMany()
                        .HasForeignKey("PerfilEstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.TablaClasificacion", null)
                        .WithMany()
                        .HasForeignKey("TablaClasificacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Estudiante", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Dominio.Estudiante", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Profesor", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Dominio.Profesor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Grupo", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Solicitudes");

                    b.Navigation("TablasClasificacion");

                    b.Navigation("Tienda")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.PerfilEstudiante", b =>
                {
                    b.Navigation("BarraProgreso")
                        .IsRequired();

                    b.Navigation("HistorialRendimientoPeriodos");
                });

            modelBuilder.Entity("Dominio.TablaEquivalencia", b =>
                {
                    b.Navigation("Equivalencias");
                });

            modelBuilder.Entity("Dominio.Tienda", b =>
                {
                    b.Navigation("Recompesas");
                });

            modelBuilder.Entity("Dominio.Estudiante", b =>
                {
                    b.Navigation("Perfiles");

                    b.Navigation("PreguntasSeguridad");
                });

            modelBuilder.Entity("Dominio.Profesor", b =>
                {
                    b.Navigation("Grupos");

                    b.Navigation("Medallas");

                    b.Navigation("TablasEquivalencia");
                });
#pragma warning restore 612, 618
        }
    }
}
