// <auto-generated />
using System;
using AccesoDatos.RepositoriosEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(ContextoDb))]
    partial class ContextoDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.BarraProgreso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("perfilEstudianteId")
                        .HasColumnType("int");

                    b.Property<int>("tablaEquivalenciaId")
                        .HasColumnType("int");

                    b.Property<int>("valorMax")
                        .HasColumnType("int");

                    b.Property<int>("valorMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("perfilEstudianteId")
                        .IsUnique();

                    b.HasIndex("tablaEquivalenciaId");

                    b.ToTable("BarrasProgreso");
                });

            modelBuilder.Entity("Dominio.EnlaceUnion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("codigoBase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("expiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("urlCompleta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EnlacesUnion");
                });

            modelBuilder.Entity("Dominio.Equivalencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("TablaEquivalenciaId")
                        .HasColumnType("int");

                    b.Property<int>("nota")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TablaEquivalenciaId");

                    b.ToTable("Equivalencias");
                });

            modelBuilder.Entity("Dominio.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProfesorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("enlaceUnionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("institucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("materia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("tablaEquivalenciaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorId")
                        .HasDatabaseName("IX_Grupo_ProfesorId");

                    b.HasIndex("enlaceUnionId");

                    b.HasIndex("nombre");

                    b.HasIndex("tablaEquivalenciaId");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("Dominio.Hito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("cantMedallasRequeridas")
                        .HasColumnType("int");

                    b.Property<int>("recompensaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("recompensaId");

                    b.ToTable("Hitos");
                });

            modelBuilder.Entity("Dominio.Medalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquivalenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("PerfilEstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("ProfesorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("RendimientoPeriodoId")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("icono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("monedasOtorgadas")
                        .HasColumnType("int");

                    b.Property<bool>("tieneAsignacionMutua")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EquivalenciaId");

                    b.HasIndex("Nombre");

                    b.HasIndex("PerfilEstudianteId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("RendimientoPeriodoId");

                    b.ToTable("Medallas");
                });

            modelBuilder.Entity("Dominio.PerfilEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstudianteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int?>("TablaClasificacionId")
                        .HasColumnType("int");

                    b.Property<int>("avatarGrupoId")
                        .HasColumnType("int");

                    b.Property<string>("enlaceAvatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("metaCalificacion")
                        .HasColumnType("int");

                    b.Property<int>("monedas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("TablaClasificacionId");

                    b.HasIndex("GrupoId", "EstudianteId")
                        .IsUnique()
                        .HasDatabaseName("UX_PerfilEstudiante_GrupoId_EstudianteId");

                    b.ToTable("PerfilesEstudiantes");
                });

            modelBuilder.Entity("Dominio.Pin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("fCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("fueUtilizado")
                        .HasColumnType("bit");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<string>("pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tiempoDeVida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pines");
                });

            modelBuilder.Entity("Dominio.PreguntaRespuestaSeguridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstudianteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("respuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EstudianteId");

                    b.ToTable("PreguntasRespuestasSeguridad");
                });

            modelBuilder.Entity("Dominio.Recompensa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PerfilEstudianteId")
                        .HasColumnType("int");

                    b.Property<int?>("TiendaId")
                        .HasColumnType("int");

                    b.Property<string>("imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("precio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("PerfilEstudianteId");

                    b.HasIndex("TiendaId");

                    b.ToTable("Recompensas");

                    b.HasDiscriminator().HasValue("Recompensa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Dominio.RendimientoPeriodo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("notaObtenida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("perfilEstudianteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("perfilEstudianteId");

                    b.ToTable("RendimientosPeriodos");
                });

            modelBuilder.Entity("Dominio.SolicitudUnion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("estudianteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("estudianteId");

                    b.ToTable("SolicitudesUnion");
                });

            modelBuilder.Entity("Dominio.TablaClasificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("medallaAsociadaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("Nombre");

                    b.HasIndex("medallaAsociadaId");

                    b.ToTable("TablasClasificacion");
                });

            modelBuilder.Entity("Dominio.TablaEquivalencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfesorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("ProfesorId");

                    b.ToTable("TablasEquivalencia");
                });

            modelBuilder.Entity("Dominio.Tienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId")
                        .IsUnique();

                    b.ToTable("Tiendas");
                });

            modelBuilder.Entity("Dominio.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("IntentosFallidos");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EstampaConcurrencia");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Correo");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("CorreoConfirmado");

                    b.Property<string>("ImagenPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("BloqueoHabilitado");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("FinBloqueo");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("CorreoNormalizado");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreUsuarioNormalizado");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContraseniaHash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Telefono");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("TelefonoConfirmado");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EstampaSeguridad");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("AutenticacionDosFactores");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreUsuario");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NombreUsuarioNormalizado] IS NOT NULL");

                    b.ToTable("Usuarios", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RolId");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EstampaConcurrencia");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreRol");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("NombreRolNormalizado");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NombreRolNormalizado] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReclamacionRolId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoReclamacion");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorReclamacion");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RolId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ReclamacionesRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReclamacionUsuarioId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoReclamacion");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorReclamacion");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ReclamacionesUsuario", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Proveedor");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ClaveProveedor");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NombreProveedor");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("IniciosSesionUsuario", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RolId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsuariosRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsuarioId");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Proveedor");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("NombreToken");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ValorToken");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("TokensUsuario", (string)null);
                });

            modelBuilder.Entity("Dominio.Potenciador", b =>
                {
                    b.HasBaseType("Dominio.Recompensa");

                    b.Property<double>("multiplicador")
                        .HasColumnType("float");

                    b.Property<DateTime>("periodo")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Potenciador");
                });

            modelBuilder.Entity("Dominio.Estudiante", b =>
                {
                    b.HasBaseType("Dominio.Usuario");

                    b.ToTable("Estudiantes", (string)null);
                });

            modelBuilder.Entity("Dominio.Profesor", b =>
                {
                    b.HasBaseType("Dominio.Usuario");

                    b.ToTable("Profesores", (string)null);
                });

            modelBuilder.Entity("Dominio.BarraProgreso", b =>
                {
                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithOne("barraProgreso")
                        .HasForeignKey("Dominio.BarraProgreso", "perfilEstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.TablaEquivalencia", "tablaEquivalencia")
                        .WithMany()
                        .HasForeignKey("tablaEquivalenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tablaEquivalencia");
                });

            modelBuilder.Entity("Dominio.Equivalencia", b =>
                {
                    b.HasOne("Dominio.TablaEquivalencia", null)
                        .WithMany("equivalencias")
                        .HasForeignKey("TablaEquivalenciaId");
                });

            modelBuilder.Entity("Dominio.Grupo", b =>
                {
                    b.HasOne("Dominio.Profesor", null)
                        .WithMany("grupos")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.EnlaceUnion", "enlaceUnion")
                        .WithMany()
                        .HasForeignKey("enlaceUnionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.TablaEquivalencia", "tablaEquivalencia")
                        .WithMany()
                        .HasForeignKey("tablaEquivalenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("enlaceUnion");

                    b.Navigation("tablaEquivalencia");
                });

            modelBuilder.Entity("Dominio.Hito", b =>
                {
                    b.HasOne("Dominio.Estudiante", null)
                        .WithMany("hitos")
                        .HasForeignKey("EstudianteId");

                    b.HasOne("Dominio.Recompensa", "recompensa")
                        .WithMany()
                        .HasForeignKey("recompensaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("recompensa");
                });

            modelBuilder.Entity("Dominio.Medalla", b =>
                {
                    b.HasOne("Dominio.Equivalencia", null)
                        .WithMany("medallasNecesarias")
                        .HasForeignKey("EquivalenciaId");

                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithMany("medallasObtenidas")
                        .HasForeignKey("PerfilEstudianteId");

                    b.HasOne("Dominio.Profesor", null)
                        .WithMany("medallas")
                        .HasForeignKey("ProfesorId");

                    b.HasOne("Dominio.RendimientoPeriodo", null)
                        .WithMany("medallasObtuvoEstudiante")
                        .HasForeignKey("RendimientoPeriodoId");
                });

            modelBuilder.Entity("Dominio.PerfilEstudiante", b =>
                {
                    b.HasOne("Dominio.Estudiante", null)
                        .WithMany("perfiles")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Grupo", null)
                        .WithMany("alumnos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.TablaClasificacion", null)
                        .WithMany("participantes")
                        .HasForeignKey("TablaClasificacionId");
                });

            modelBuilder.Entity("Dominio.PreguntaRespuestaSeguridad", b =>
                {
                    b.HasOne("Dominio.Estudiante", null)
                        .WithMany("preguntasSeguridad")
                        .HasForeignKey("EstudianteId");
                });

            modelBuilder.Entity("Dominio.Recompensa", b =>
                {
                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithMany("inventario")
                        .HasForeignKey("PerfilEstudianteId");

                    b.HasOne("Dominio.Tienda", null)
                        .WithMany("Recompesas")
                        .HasForeignKey("TiendaId");
                });

            modelBuilder.Entity("Dominio.RendimientoPeriodo", b =>
                {
                    b.HasOne("Dominio.PerfilEstudiante", null)
                        .WithMany("historialRendimientoPeriodos")
                        .HasForeignKey("perfilEstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LogicaNegocio.ValueObject.RangoFechas", "rangofecha", b1 =>
                        {
                            b1.Property<int>("RendimientoPeriodoId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("fechaFin")
                                .HasColumnType("datetime2")
                                .HasColumnName("FechaFin");

                            b1.Property<DateTime>("fechaInicio")
                                .HasColumnType("datetime2")
                                .HasColumnName("FechaInicio");

                            b1.HasKey("RendimientoPeriodoId");

                            b1.ToTable("RendimientosPeriodos");

                            b1.WithOwner()
                                .HasForeignKey("RendimientoPeriodoId");
                        });

                    b.Navigation("rangofecha")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.SolicitudUnion", b =>
                {
                    b.HasOne("Dominio.Grupo", "Grupo")
                        .WithMany("solicitudes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Estudiante", "estudiante")
                        .WithMany()
                        .HasForeignKey("estudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("estudiante");
                });

            modelBuilder.Entity("Dominio.TablaClasificacion", b =>
                {
                    b.HasOne("Dominio.Grupo", null)
                        .WithMany("tablasClasificacion")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Medalla", "medallaAsociada")
                        .WithMany()
                        .HasForeignKey("medallaAsociadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("medallaAsociada");
                });

            modelBuilder.Entity("Dominio.TablaEquivalencia", b =>
                {
                    b.HasOne("Dominio.Profesor", null)
                        .WithMany("tablasEquivalencia")
                        .HasForeignKey("ProfesorId");
                });

            modelBuilder.Entity("Dominio.Tienda", b =>
                {
                    b.HasOne("Dominio.Grupo", null)
                        .WithOne("tienda")
                        .HasForeignKey("Dominio.Tienda", "GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Usuario", b =>
                {
                    b.OwnsOne("LogicaNegocio.ValueObjects.NombreCompleto", "NombreCompleto", b1 =>
                        {
                            b1.Property<string>("UsuarioId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Apellido");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Nombre");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("NombreCompleto")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Estudiante", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Dominio.Estudiante", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Profesor", b =>
                {
                    b.HasOne("Dominio.Usuario", null)
                        .WithOne()
                        .HasForeignKey("Dominio.Profesor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Equivalencia", b =>
                {
                    b.Navigation("medallasNecesarias");
                });

            modelBuilder.Entity("Dominio.Grupo", b =>
                {
                    b.Navigation("alumnos");

                    b.Navigation("solicitudes");

                    b.Navigation("tablasClasificacion");

                    b.Navigation("tienda")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.PerfilEstudiante", b =>
                {
                    b.Navigation("barraProgreso")
                        .IsRequired();

                    b.Navigation("historialRendimientoPeriodos");

                    b.Navigation("inventario");

                    b.Navigation("medallasObtenidas");
                });

            modelBuilder.Entity("Dominio.RendimientoPeriodo", b =>
                {
                    b.Navigation("medallasObtuvoEstudiante");
                });

            modelBuilder.Entity("Dominio.TablaClasificacion", b =>
                {
                    b.Navigation("participantes");
                });

            modelBuilder.Entity("Dominio.TablaEquivalencia", b =>
                {
                    b.Navigation("equivalencias");
                });

            modelBuilder.Entity("Dominio.Tienda", b =>
                {
                    b.Navigation("Recompesas");
                });

            modelBuilder.Entity("Dominio.Estudiante", b =>
                {
                    b.Navigation("hitos");

                    b.Navigation("perfiles");

                    b.Navigation("preguntasSeguridad");
                });

            modelBuilder.Entity("Dominio.Profesor", b =>
                {
                    b.Navigation("grupos");

                    b.Navigation("medallas");

                    b.Navigation("tablasEquivalencia");
                });
#pragma warning restore 612, 618
        }
    }
}
