<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ImplementacionCasosUsos\Usuarios\**" />
    <Compile Remove="InterfacesCasosUsos\Usuario\**" />
    <EmbeddedResource Remove="ImplementacionCasosUsos\Usuarios\**" />
    <EmbeddedResource Remove="InterfacesCasosUsos\Usuario\**" />
    <None Remove="ImplementacionCasosUsos\Usuarios\**" />
    <None Remove="InterfacesCasosUsos\Usuario\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogicaNegocio\LogicaNegocio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\AtributoAvatarDTOs\" />
    <Folder Include="DTOs\ImagenDTOs\" />
    <Folder Include="DTOs\RestablecerContrasenaDTO\" />
    <Folder Include="ImplementacionCasosUsos\Avatar\" />
    <Folder Include="ImplementacionCasosUsos\Imagenes\Estrategias\" />
    <Folder Include="ImplementacionCasosUsos\Login\" />
    <Folder Include="ImplementacionCasosUsos\RecuperarContrasena\" />
    <Folder Include="InterfacesCasosUsos\Kudo\" />
    <Folder Include="InterfacesCasosUsos\RecuperarContrasena\" />
    <Folder Include="InterfacesCasosUsos\ServicioPrecargaArchivos\" />
  </ItemGroup>

</Project>
