<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogicaNegocio\LogicaNegocio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\AvatarDTOs\" />
    <Folder Include="ImplementacionCasosUsos\Avatar\" />
    <Folder Include="ImplementacionCasosUsos\Usuarios\" />
    <Folder Include="InterfacesCasosUsos\Imagenes\" />
    <Folder Include="InterfacesCasosUsos\Usuario\" />
  </ItemGroup>

</Project>
